[package]
name = "zeroklue_circuits"
type = "bin"
authors = ["ZeroKlue Team"]
compiler_version = ">=1.0.0-beta.0"

[dependencies]
# EdDSA signature verification (latest stable)
eddsa = { git = "https://github.com/noir-lang/eddsa", tag = "v0.1.3" }

# NOTE: Poseidon is now in std::hash::poseidon
# See: https://noir-lang.org/docs/noir/standard_library/cryptographic_primitives/hashes
