[package]
name = "zeroklue_circuits"
type = "bin"
authors = ["ZeroKlue Team"]
compiler_version = ">=0.38.0"

[dependencies]
# EdDSA signature verification
eddsa = { git = "https://github.com/noir-lang/eddsa", tag = "v0.1.0" }
# Poseidon hashing (comes with std but we may need extended versions)
# See: https://github.com/noir-lang/poseidon
